firstApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('upload_book/', views.upload_book, name='upload_book'),
    path('books/', views.books, name='books'),
    path('transactions/', views.transactions, name='transactions'),
    path('site_admin/', views.site_admin, name='site_admin'),
    
    
    

]    

firstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('firstApp/', include('firstApp.urls')),
    path('admin/', admin.site.urls),
    #path('accounts/', include('allauth.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('social_django.urls', namespace='social')),
    
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=100)
    TYPE = (
        ('BK', 'Book'),
        ('AU', 'Audio'),
    )
    type = models.CharField(max_length=6, choices = TYPE, default = "Book")
    genre = models.CharField(max_length=100)
    isbn_number = models.CharField(max_length=13)
    sales = models.IntegerField(default = 0)
    publish_date = models.DateField(blank=True, null=True)
    description = models.TextField(default="")
    price = models.IntegerField(default=0)
    document = models.FileField(upload_to='books/')
    book_pic = models.ImageField(upload_to = 'bookimages/', default = 'pic_folder/None/no-img.jpg')        
    audio_file =  models.FileField(upload_to = 'audiofiles/', default = "", null = True, blank = True)
    
class Transaction(models.Model):
    Book = models.ForeignKey(Book, on_delete=models.CASCADE)
    buyer = models.CharField(max_length=100)
    transaction_id = models.AutoField(max_length=90, primary_key = True)
    time = models.TimeField(auto_now_add=True)
    purchase_date = models.DateField(auto_now_add=True)

'''class User(models.Model):
    username = models.CharField(max_length=50)
    PREVILAGES = (
        ('SU', 'Super Admin'),
        ('ED', 'Editor'),
    )
    previlages = models.CharField(choices = PREVILAGES, max_length=10)
    activation = models.BooleanField()'''

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

'''class Profile(models.Model):
    profile_id = models.PositiveIntegerField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    PREVILAGES = (
        ('SU', 'Super Admin'),
        ('admin', 'Admin'),
    )
    previlages = models.CharField(choices = PREVILAGES, max_length=20, default='admin')
   

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()'''

firstApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from firstApp.models import *


class SignUpForm(UserCreationForm):
    
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'type', 'genre', 'isbn_number', 'publish_date', 'description', 'price', 'book_pic','document', 'audio_file',
    )

'''class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('previlages',)'''

firstApp/views/books.py
from django.shortcuts import render, redirect
from firstApp.models import Book

def books(request):
    book = Book.objects.all()



    
    return render(request, 'firstApp/books.html',{'books':book})

firstApp/views/dashboard.py
from django.shortcuts import render, redirect

def dashboard(request):
    
    return render(request, 'firstApp/dashboard.html')

firstApp/views/sales.py
from django.shortcuts import render, redirect

firstApp/views/site_admin.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from firstApp.forms import *


def site_admin(request):
    if request.method == 'POST':
        user_form = SignUpForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return redirect('')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = SignUpForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    '''if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('')
    else:
        form = SignUpForm()'''
    return render(request, 'firstApp/site_admin.html', {'user_form': user_form,
        'profile_form': profile_form} )

firstApp/views/transactions.py
from django.shortcuts import render, redirect
def transactions(request):
    
    return render(request, 'firstApp/transactions.html')

firstApp/views/upload_book.py
from django.shortcuts import render, redirect
from firstApp.forms import BookForm
def upload_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('upload_book')
    else:
        form = BookForm()
    return render(request, 'firstApp/upload.html', {
        'form': form })

firstApp/templates/authtemplate.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <link rel="shortcut icon" href="img/favicon_1.ico">

        <title>{% block title %}{% endblock %}</title>

         <!-- Google-Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:100,300,400,600,700,900,400italic' rel='stylesheet'>

        <!-- Bootstrap core CSS -->
        <link href=" {% static 'css/bootstrap.min.css' %} " rel="stylesheet">
        <link href=" {% static 'css/bootstrap-reset.css' %} " rel="stylesheet">

        <!--Animation css-->
        <link href=" {% static 'css/animate.css' %} " rel="stylesheet">
        <link href=" {% static 'css/custom.css' %} " rel="stylesheet">

        <!--Icon-fonts css-->
        <link href=" {% static 'assets/font-awesome/css/font-awesome.css' %} " rel="stylesheet" />
        <link href= "{% static 'assets/ionicon/css/ionicons.min.css' %} " rel="stylesheet" />

        <!--Data table css-->
        <link href="{% static 'assets/datatables/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css" />
        

        <!--Morris Chart CSS -->
        <link rel="stylesheet" href= "{% static 'assets/morris/morris.css' %} ">

        <!-- sweet alerts -->
        <link href="{% static 'assets/sweet-alert/sweet-alert.min.css' %} " rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href=" {% static 'css/style.css' %} " rel="stylesheet">
        <link href=" {% static 'css/helper.css' %}" rel="stylesheet">
        <link href=" {% static 'css/style-responsive.css' %}" rel="stylesheet" />

        <!--Togglers -->
        <link href="{% static 'assets/toggles/toggles.css' %}" rel="stylesheet" />





    </head>


    <body>

            {% block content %}{% endblock %}

       

    
 <!-- js placed at the end of the document so the pages load faster -->
        <script src=" {% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/modernizr.min.js' %} "></script>
        <script src="{% static 'js/pace.min.js' %}"></script>
        <script src="{% static 'js/wow.min.js' %}"></script>
        <script src="{% static 'js/jquery.scrollTo.min.js' %} "></script>
        <script src="{% static 'js/jquery.nicescroll.js' %} " type="text/javascript"></script>
        
        <!-- Counter-up -->
        <script src="{% static 'js/waypoints.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/jquery.counterup.min.js' %} " type="text/javascript"></script>

        
        
        <script src="{% static 'js/jquery.app.js' %}"></script>
        <!-- Chat -->
        <script src="{% static 'js/jquery.chat.js' %} "></script>
        <!-- Dashboard -->
        
        <!-- Todo -->
        <script src="{% static 'js/jquery.todo.js' %} "></script>
        
        <script src="{% static 'assets/toggles/toggles.min.js' %}"></script>

        <!--Table Javascript-->
        <script src="{% static 'assets/datatables/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'assets/datatables/dataTables.bootstrap.js' %}"></script>
        
        <script src="{% static 'assets/flot-chart/jquery.flot.js' %}"></script>
        <script src="{% static 'assets/flot-chart/jquery.flot.time.js' %}"></script>
        <script src="{% static 'assets/flot-chart/jquery.flot.tooltip.min.js' %}"></script>
        <script src="{% static 'assets/flot-chart/jquery.flot.resize.js' %}"></script>
        <script src="{% static 'assets/flot-chart/jquery.flot.pie.js' %}"></script>
        <script src="{% static 'assets/flot-chart/jquery.flot.selection.js' %}"></script>
        <script src="{% static 'assets/flot-chart/jquery.flot.stack.js' %}"></script>
        <script src="{% static 'assets/flot-chart/jquery.flot.crosshair.js' %}"></script>
        <script src="{% static 'assets/flot-chart/jquery.flot.init.js' %}"></script>
    
    </body>

<!-- Mirrored from coderthemes.com/velonic_3.0/admin/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 29 Jan 2018 06:32:54 GMT -->
</html>

firstApp/templates/firstApp/books.html
{% extends "index.html" %}
{% block title %}The current time{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
                <form role="search" class="app-search">
                        <input type="text" placeholder="Search..." class="form-control">
                </form>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-2 col-lg-offset-2 col-sm-6">
            <div class="widget-panel widget-style-2 bg-pink">
                 
                <h2 class="m-0 counter">50</h2>
                <div>Daily Visits</div>
            </div>
        </div>
        <div class="col-lg-2 col-sm-6">
            <div class="widget-panel widget-style-2 bg-purple">
                 
                <h2 class="m-0 counter">12056</h2>
                <div>Sales</div>
            </div>
        </div>
        <div class="col-lg-2 col-sm-6">
            <div class="widget-panel widget-style-2 bg-info">
                 
                <h2 class="m-0 counter">1268</h2>
                <div>New Orders</div>
            </div>
        </div>
        <div class="col-lg-2 col-sm-6">
            <div class="widget-panel widget-style-2 bg-success">
                 
                <h2 class="m-0 counter">145</h2>
                <div>New Users</div>
            </div>
        </div>
    </div> <!-- end row -->

    <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <table id="datatable" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Title</th>
                                            <th>Author</th>
                                            <th>Type</th>
                                            <th>Genre</th>
                                            <th>ISBN-NO</th>
                                            <th>Sales</th>
                                            <th>Publish Date</th>
                                            <th>Price</th>
                                        </tr>
                                    </thead>

                             
                                    <tbody>
                                        {% for book in books %}
                                        <tr>
                                            <td>{{book.title}}</td>
                                            <td>{{book.author}}</td>
                                            <td>{{book.type}}</td>
                                            <td>{{book.genre}}</td>
                                            <td>{{book.isbn_number}}</td>
                                            <td>{{book.sales}}</td>
                                            <td>{{book.publish_date}}</td>
                                            <td>{{book.price}}</td>
                                        </tr>
                                        {% endfor %}
                                        
                          
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div> <!-- End Row -->



{% endblock %}

firstApp/templates/firstApp/dashboard.html
{% extends "index.html" %}
{% block title %}The current time{% endblock %}
{% block content %}

        <!-- Row start -->
        <div class="row">
                <div class="col-md-8">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Book Sales</h3>
                            </div>
                            <div class="panel-body">
                            
                                    <div class="row">
                                            <div class="col-lg-3 col-sm-6">
                                                <div class="widget-panel widget-style-2 bg-pink">
                                                    
                                                    <h2 class="m-0 counter">50</h2>
                                                    <div>Books sold</div>
                                                </div>
                                            </div>
                                            <div class="col-lg-3 col-sm-6">
                                                <div class="widget-panel widget-style-2 bg-purple">
                                                     
                                                    <h2 class="m-0 counter">12056</h2>
                                                    <div>Audios sold</div>
                                                </div>
                                            </div>
                                            <div class="col-lg-3 col-sm-6">
                                                <div class="widget-panel widget-style-2 bg-info">
                                                   
                                                    <h2 class="m-0 counter">1268</h2>
                                                    <div>Books published</div>
                                                </div>
                                            </div>
                                            <div class="col-lg-3 col-sm-6">
                                                <div class="widget-panel widget-style-2 bg-success">
                                                    
                                                    <h2 class="m-0 counter">145</h2>
                                                    <div>Audios published</div>
                                                </div>
                                            </div>
                                        </div>
                            </div>
                        </div>
                        <div class="portlet"><!-- /primary heading -->
                            <div class="portlet-heading">
                                <h3 class="portlet-title text-dark text-uppercase">
                                    Transactions
                                </h3>
                                <div class="portlet-widgets">
                                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                                    <span class="divider"></span>
                                    <a data-toggle="collapse" data-parent="#accordion1" href="#portlet5"><i class="ion-minus-round"></i></a>
                                    <span class="divider"></span>
                                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div id="portlet5" class="panel-collapse collapse in">
                                <div class="portlet-body">
                                    <div id="combine-chart">
                                        <div id="combine-chart-container" class="flot-chart" style="height: 180px;">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- /Portlet -->
                </div>
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Latest Activities</h3>
                        </div>
                        <div class="panel-body">
                                <div class="row">
                                        <div class="col-md-12 col-sm-12 col-xs-12">
                                            <table class="table table-hover">
                                                
                                                <tbody>
                                                    <tr>
                                                        <td>Mark</td>
                                                        <td>Otto</td>
                                                        <td>@mdo</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Jacob</td>
                                                        <td>Thornton</td>
                                                        <td>@fat</td>
                                                    </tr>
                                                    <tr>
                                                        <td>3</td>
                                                        <td >Larry the Bird</td>
                                                        <td>@twitter</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Steve</td>
                                                        <td>Urkel</td>
                                                        <td>@steve</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Steve</td>
                                                        <td>Urkel</td>
                                                        <td>@steve</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Steve</td>
                                                        <td>Urkel</td>
                                                        <td>@steve</td>
                                                    </tr>
                                                    <tr>
                                                        <td>Steve</td>
                                                        <td>Urkel</td>
                                                        <td>@steve</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>    
                        </div>
                    </div>
                </div>
                
            </div>
{% endblock %}

firstApp/templates/firstApp/site_admin.html
{% extends "index.html" %}
{% block title %}The current time{% endblock %}
{% block content %}
<div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                        <div class="row ">
                                <div class="col-md-6">
                                        <h1 class="panel-title">Site Admins</h1>
                                </div>
                                <div class="col-md-6 text-right">
                                        <button type="button" class="btn btn-success btn-rounded m-b-5" data-toggle="modal" data-target="#con-close-modal">Add Users</button>
                                        
                                </div>
                            </div>
                </div>
                <div class="panel-body">
                    
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>USERNAME</th>
                                            <th>PRIVELEGES</th>
                                            <th>ACTIVATIONS</th>
                                        </tr>
                                    </thead>
                                    <tbody >
                                        <tr>
                                            <td>@mdo</td>
                                            <td>20</td>
                                            <td>                                                
                                                    <label class="switch">
                                                            <input type="checkbox" checked>
                                                            <span class="slider round"></span>
                                                    </label>
                                             
                                            </td>
                                        </tr>
                                        <tr>
                                            
                                            <td>@fat</td>
                                            <td>20</td>
                                            <td>
                                                    <label class="switch">
                                                            <input type="checkbox" checked>
                                                            <span class="slider round"></span>
                                                    </label>
                                            </td>
                                        </tr>
                                        <tr>
                                            
                                            <td>@twitter</td>
                                            <td>20</td>
                                            <td>
                                                <label class="switch">
                                                    <input type="checkbox" checked>
                                                    <span class="slider round"></span>
                                            </label>
                                        </td>
                                        </tr>
                                        <tr>
                                            <td>@steve</td>
                                            <td>20</td>
                                            <td>
                                                    <label class="switch">
                                                            <input type="checkbox" checked>
                                                            <span class="slider round"></span>
                                                    </label>
                                            </td>
                                        </tr>
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End row -->

    <div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog"> 
            <div class="modal-content"> 
                <div class="animated fadeInDown">
                    <div class="panel panel-color panel-primary">
                        <div class="panel-heading"> 
                           <h3 class="text-center m-t-10"> HozyBook Web </h3>
                        </div> 
        
                        <form class="form-horizontal m-t-40" method="post" action="">
                                
                                      {% csrf_token %}
                                      
                            {% if form.errors %}
                            <div class="form-group ">
                                <div class="col-xs-12">
                                    <p class=" label label-danger">
                                        Your username and password didn't match. 
                                        Please try again.
                                    </p>
                                </div>
                            </div>        
                            {% endif %}
                            <div class="form-group select-border">
                                <div class="col-xs-12">
                                    <input class="form-control" for="id_username" id="id_username" name="username" type="text" placeholder="Username" required>
                                </div>
                            </div>
                            <div class="form-group select-border">
                                <div class="col-xs-12">
                                    <input class="form-control" for="id_email" id="id_email" name="email" type="email" placeholder="Email" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-12">
                                        <select class="form-control" name="previlages" id="id_previlages" for="id_previlages">
                                            <option>Super Admin</option>
                                            <option>Admin</option>
                                            <option>Editor</option>
                                            
                                        </select>
                                        
                                </div>
                            </div>
                            <div class="form-group select-border">
                                
                                <div class="col-xs-12">
                                    <input class="form-control" for="id_password1" type="password" id="id_password1" name="password1" placeholder="Password" required>
                                </div>
                            </div>
                            <div class="form-group ">
                                
                                <div class="col-xs-12">
                                    <input class="form-control" for="id_password2" type="password" id="id_password2" name="password2" placeholder="Confirm Password" required>
                                </div>
                            </div>                    
                            
        
                                              
                            
                            
                            
                            <div class="form-group text-right">
                                <div class="col-xs-12">
                                    <button class="btn btn-purple w-md" type="submit">Create Account</button>
                                </div>
                            </div>
                           
                        </form>
        
                    </div>
                </div> 
            </div> 
        </div>
    </div><!-- /.modal -->
{% endblock %}

firstApp/templates/firstApp/upload_form.html
<|>